# enabled true on an app is to tell helm to create an argo app cr for this item
applications:
  - name: nexus
    enabled: true
    source: https://github.com/rht-labs/ubiquitous-journey
    source_path: charts/ubiquitous-journey
    source_ref: master
    sync_policy_automated: true
    valueFiles:
    - apps/nexus/values.yaml
  - name: jenkins
    enabled: true 
    source: https://github.com/rht-labs/ubiquitous-journey
    source_path: charts/ubiquitous-journey
    source_ref: master
    sync_policy_automated: true
    valueFiles:
    - apps/jenkins/values.yaml
    ignore_differences:
      ignoreDifferences:
        - group: apps.openshift.io
          kind: DeploymentConfig
          jsonPointers:
          - /spec/template/spec/containers/0/image
          - /spec/triggers/0/imageChangeParams/lastTriggeredImage
        - group: build.openshift.io
          kind: BuildConfig
          jsonPointers:        
          - /spec/triggers
          - /status
  - name: sonarqube
    enabled: true 
    source: https://github.com/rht-labs/ubiquitous-journey
    source_path: charts/ubiquitous-journey
    source_ref: master
    sync_policy_automated: true
    valueFiles:
    - apps/sonarqube/values.yaml
