# Over rides for default values in Helm Charts
destination_test: &test_ns labs-test
destination_staging: &staging_ns labs-staging
helm_repository: &helm_repo "https://nexus-labs-ci-cd.apps.hivec.sandbox1559.opentlc.com/repository/helm-charts/"
destination: &test_ns labs-test
##############
# Application Custom Values
#############
# toggle between versions of the app by setting the tag to grey / purple or latest
pet_battle: &front_end_values
  app_tag: latest
  # Could be over written in a jenkins file or your fork when doing CI/CD 
  # image_repository: image-registry.openshift-image-registry.svc:5000
  # image_name: pet-battle
  # image_namespace: labs-ci-cd
  config_map: "'http://pet-battle-api-labs-dev.apps.hivec.sandbox1559.opentlc.com/'"
pet_battle_api: &api_values
  appName: pet-battle-api
  image_repository: quay.io
  image_name: pet-battle-api
  image_namespace: eformat
  image_version: latest
##############
# Argo Ignore Differences
#############
ignore_differences: &ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
    - /spec/triggers/1/imageChangeParams/lastTriggeredImage
##############
# Argo App of Apps declaration
#############
applications:
- name: test-pet-battle
  enabled: true
  source: https://github.com/springdo/pet-battle.git
  source_path: chart
  sync_policy_automated: true
  destination: *test_ns
  source_ref: master
  values: *front_end_values
  ignore_differences: *ignore_differences
- name: test-pet-battle-api
  enabled: true
  source: *helm_repo
  source_path: ""
  chart_name: pet-battle-api
  sync_policy_automated: true
  destination: *test_ns
  source_ref: 1.0.0
  ignore_differences: *ignore_differences
- name: pet-battle
  enabled: true
  source: https://github.com/springdo/pet-battle.git
  source_path: chart
  sync_policy_automated: true
  destination: *staging_ns
  source_ref: master
  values: *front_end_values
  ignore_differences: *ignore_differences
- name: pet-battle-api
  enabled: true
  source: *helm_repo
  source_path: ""
  chart_name: pet-battle-api # probs over written in jenkins
  sync_policy_automated: true
  destination: *staging_ns
  source_ref: 1.0-SNAPSHOT
  ignore_differences: *ignore_differences
