# Over rides for default values in Helm Charts
destination: &ci_cd_ns labs-ci-cd

##############
# 🛎 Jenkins Custom Values
#############
jenkins_values: &jenkins_values
  source_secrets:
    - name: git-auth
      username: foo
      password: bar
    - name: nexus-password
      username: admin
      password: admin123
    - name: argocd-token
      username: token
      password: foobar
  buildconfigs:
    - name: jenkins
      build_trigger_secret: 'shhhhh-this-is-my-super-duper-secret123-shhhhh'
      strategy_type: "Source"
      source_secret: 'git-auth'
      pull_secret: ''
      source_repo: https://github.com/eformat/enablement-ci-cd.git
      source_repo_ref: 4.3
      source_context_dir: 'jenkins-s2i'
      builder_image_name: jenkins
      builder_image_tag: '2'
    - name: "jenkins-slave-mvn"
      strategy_type: "Docker"
      source_context_dir: "jenkins-slaves/jenkins-slave-mvn"
      source_repo: "https://github.com/redhat-cop/containers-quickstarts"
      source_repo_ref: "v1.22"
      builder_image_name: "quay.io/eformat/origin-jenkins-agent-maven"
      builder_image_tag: "latest"
    - name: "jenkins-slave-helm"
      strategy_type: "Docker"
      source_context_dir: "jenkins-slaves/jenkins-slave-helm"
      source_repo: "https://github.com/redhat-cop/containers-quickstarts"
      source_repo_ref: "master"
      builder_image_name: "quay.io/openshift/origin-jenkins-agent-base"
      builder_image_tag: "4.3"
    - name: "jenkins-slave-argocd"
      strategy_type: "Docker"
      source_context_dir: "jenkins-slaves/jenkins-slave-argocd"
      source_repo: "https://github.com/redhat-cop/containers-quickstarts"
      source_repo_ref: "master"
      builder_image_name: "quay.io/openshift/origin-jenkins-agent-base"
      builder_image_tag: "4.3"  
    - name: "jenkins-slave-npm"
      strategy_type: "Docker"
      source_context_dir: "jenkins-slaves/jenkins-slave-npm"
      source_repo: "https://github.com/redhat-cop/containers-quickstarts"
      source_repo_ref: "master"
      builder_image_name: "openshift/jenkins-slave-base-centos7"
      builder_image_tag: "v3.11"

##############
# 🛎 Pact Broker Custom Values
#############
pact_broker_values: &pact_broker_values
  secrets:
    name: pact-broker-secrets
    keys:
      pactBrokerDatabaseUsername: pact_broker_database_username
      pactBrokerDatabasePassword: pact_broker_database_password
      pactBrokerAdmin: pact_broker_admin
      pactBrokerAdminPassword: pact_broker_admin_password
      pactBrokerBasicAuthUsername: pact_broker_user
      pactBrokerBasicAuthPassword: pact_broker_user_password
    values:
      pactBrokerDatabaseUsername: pact_broker_user
      pactBrokerDatabasePassword: thisisdefinitelynotmypassword
      pactBrokerAdmin: admin
      pactBrokerAdminPassword: thisisdefinitelynotmypassword
      pactBrokerBasicAuthUsername: dev
      pactBrokerBasicAuthPassword: thisisdefinitelynotmypassword

##############
# 🛎 Zalenium Custom Values
#############
## TODO: Update source URL as upstream when ArgoCD version is greater 1.5.0 or above
zalenium_values: &zalenium_values
  hub:
    serviceType: ClusterIP
    openshift:
      deploymentConfig:
        enabled: true
      route:
        enabled: true
    persistence:
      enabled: false
    serviceAccount:
      create: false
    desiredContainers: 0
    podAnnotations:
      app: zalenium

##############
# 🛎 Hoverfly Custom Values
# Values reference https://github.com/helm/charts/tree/master/incubator/hoverfly
#############
hoverfly_values: &hoverfly_values
  replicaCount: "1"
  openshift:
    route:
      admin:
        enabled: true
        hostname: ""
      proxy:
        enabled: true
        hostname: ""

##############
# 🛎 Wekan Custom Values
# Values reference https://github.com/wekan/wekan/tree/master/helm/wekan
#############
wekan_values: &wekan_values
  service:
    type: ClusterIP
  autoscaling:
    enabled: false
  mongodb-replicaset:
    replicas: 1
    securityContext:
      runAsUser: ""
      fsGroup: ""
  ingress:
    enabled: false
  route:
    enabled: true

##############
# 🛎 Mattermost Custom Values
# Values reference https://github.com/mattermost/mattermost-helm
#############
mattermost_values: &mattermost_values
  route:
    enabled: true
  mysql:
    mysqlRootPassword: "mysqlpass"
    mysqlUser: "mattermost"
    mysqlPassword: "matterpass"

##############
# 🛎 Owncloud Custom Values
#############
owncloud_values: &owncloud_values
  route:
    enabled: true
  hostname: owncloud.apps.hivec.sandbox1559.opentlc.com

##############
# 🐙 Argo Ignore Differences
#############
jenkins_ignore_differences: &jenkins_ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
  - group: build.openshift.io
    kind: BuildConfig
    jsonPointers:
    - /spec/triggers
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /spec/source/helm/values

nexus_ignore_differences: &nexus_ignore_differences
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress

hoverflyignore_differences: &hoverfly_ignore_differences
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress
    - /spec/host
  - group: apps/v1
    kind: Deployment
    jsonPointers:
    - /spec/replicas

crw_ignore_differences: &crw_ignore_differences
  ignoreDifferences:
  - group: org.eclipse.che
    kind: CheCluster
    jsonPointers:
    - /spec

dev-ex-dashboard_ignore_differences: &dev-ex-dashboard_ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
  - group: ''
    kind: ConfigMap
    jsonPointers:
    - /data

owncloud_ignore_differences: &owncloud_ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage

##############
# 🐙 Argo Sync Policy
#############
sync_policy_true: &sync_policy_true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      validate: true

sync_policy_no_selfheal: &sync_policy_no_selfheal
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      validate: true

##############
# 🛎 Argo App of Apps declaration
#############

# enabled true on an app is to tell helm to create an argo app cr for this item
applications:
  - name: nexus
    enabled: true
    source: https://eformat.github.io/helm-charts/
    chart_name: sonatype-nexus
    source_path: ""
    source_ref: "0.0.2"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    ignore_differences: *nexus_ignore_differences
  - name: jenkins
    enabled: true
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/jenkins
    source_ref: "jenkins-0.0.12"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    values:
      *jenkins_values
    ignore_differences: *jenkins_ignore_differences
  - name: pact-broker
    enabled: true
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/pact-broker
    source_ref: "pact-broker-0.0.2"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    values:
      *pact_broker_values
  - name: sonarqube
    enabled: true
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/sonarqube
    source_ref: "sonarqube-0.0.4"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
  - name: crw
    enabled: true
    destination: crw
    source: https://github.com/rht-labs/refactored-adventure
    source_path: crw/base
    source_ref: master
    sync_policy:
      *sync_policy_no_selfheal
    no_helm: true
    ignore_differences: *crw_ignore_differences
  - name: zalenium
    enabled: true
    source: https://github.com/zalando/zalenium.git
    source_path: charts/zalenium
    source_ref: "master"
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    values:
      *zalenium_values
  - name: hoverfly
    enabled: true
    source: https://github.com/helm/charts.git
    source_path: incubator/hoverfly
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    source_ref: "master"
    values:
      *hoverfly_values
    ignore_differences: *hoverfly_ignore_differences
  - name: wekan
    enabled: true
    source: https://github.com/wekan/wekan.git
    source_path: helm/wekan
    sync_policy:
      *sync_policy_true
    destination: *ci_cd_ns
    source_ref: "v4.01"
    values:
      *wekan_values
  - name: tekton
    enabled: true
    destination: crw
    source: https://github.com/rht-labs/refactored-adventure
    source_path: tekton/base
    source_ref: master
    sync_policy:
      *sync_policy_true
    no_helm: true
  - name: mattermost
    enabled: true
    source: https://github.com/mattermost/mattermost-helm.git
    source_path: charts/mattermost-team-edition
    destination: *ci_cd_ns
    source_ref: "mattermost-team-edition-3.10.0"
    values:
      *mattermost_values
  - name: etherpad
    enabled: true
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/etherpad
    destination: *ci_cd_ns
    source_ref: "etherpad-0.0.1"
    sync_policy:
      *sync_policy_true
  - name: dev-ex-dashboard
    enabled: true
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/dev-ex-dashboard
    destination: *ci_cd_ns
    source_ref: "dev-ex-dashboard-0.0.1"
    sync_policy:
      *sync_policy_no_selfheal
    ignore_differences: *dev-ex-dashboard_ignore_differences
  - name: owncloud
    enabled: true
    source: https://github.com/rht-labs/helm-charts.git
    source_path: charts/owncloud
    destination: *ci_cd_ns
    source_ref: "owncloud-0.0.1"
    sync_policy:
      *sync_policy_true
    ignore_differences: *owncloud_ignore_differences
    values:
      *owncloud_values
